apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-security-controller.fullname" . }}-agent
  labels:
    {{- include "k8s-security-controller.labels" . | nindent 4 }}
    component: agent
spec:
  type: ClusterIP
  selector:
    {{- include "k8s-security-controller.selectorLabels" . | nindent 4 }}
    component: agent
  ports:
    - name: falco-webhook
      port: 2801
      targetPort: 2801
      protocol: TCP
