apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-security-controller.fullname" . }}-config
  labels:
    {{- include "k8s-security-controller.labels" . | nindent 4 }}
data:
  security-config.yaml: |
    cron:
      enabled: {{ .Values.cron.enabled }}
      monitoringInterval: {{ .Values.cron.monitoringInterval }}
      monitoredPaths:
{{- range .Values.cron.monitoredPaths }}
        - "{{ . }}"
{{- end }}
      suspiciousPatterns:
{{- range .Values.cron.suspiciousPatterns }}
        - "{{ . }}"
{{- end }}
      allowedCommands:
{{- range .Values.cron.allowedCommands }}
        - "{{ . }}"
{{- end }}
    logging:
      level: "info"
    # File monitor confg
    fileMonitoring:
      enabled: {{ .Values.fileMonitoring.enabled }}
      monitoringInterval: {{ .Values.fileMonitoring.monitoringInterval }}
      forbiddenExtensions:
{{- range .Values.fileMonitoring.forbiddenExtensions }}
        - "{{ . }}"
{{- end }}
      protectedPaths:
{{- range .Values.fileMonitoring.protectedPaths }}
        - "{{ . }}"
{{- end }}
      allowedWritePaths:
{{- range .Values.fileMonitoring.allowedWritePaths }}
        - "{{ . }}"
{{- end }}
      maxFileSize: {{ .Values.fileMonitoring.maxFileSize }}
    # Secret monitor confg
    falcoWebhook:
      enabled: {{ .Values.falcoWebhook.enabled }}
      listenAddr: {{ .Values.falcoWebhook.listenAddr | quote }}
      secret: {{ .Values.falcoWebhook.secret | quote }}
      actions:
        deletePod: {{ .Values.falcoWebhook.actions.deletePod }}
        terminateProcess: {{ .Values.falcoWebhook.actions.terminateProcess }}


