apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-security-controller.fullname" . }}
  labels:
    {{- include "k8s-security-controller.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-security-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "k8s-security-controller.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "k8s-security-controller.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SECURITY_PROFILES_RCE
              value: "{{ .Values.controller.securityProfiles.rceProtection }}"
            - name: SECURITY_PROFILES_MINING
              value: "{{ .Values.controller.securityProfiles.miningProtection }}"
            - name: MONITORING_LOG_LEVEL
              value: "{{ .Values.monitoring.logLevel }}"
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
